// Fictional license agreement data — SEC/DART style shapes.
// All company names are invented. Accession/receipt numbers are fake but
// formatted to match real patterns (EDGAR: NNNNNNNNNN-YY-NNNNNN, DART: 14-digit rcept_no).

const SNAPSHOT = {
  raw_extractions: 38114,
  clean_agreements: 19054,
  companies: 2186,
  royalty_observations: 1546,
  real_license_rate: 0.793,
  as_of: "2026-04-15",
  sources: {
    sec_filings: 142318,
    dart_filings: 28976,
    unified_mapped: 18490,
  },
};

const AGREEMENTS = [
  {
    id: "AGR-04812",
    licensor: "Helixon Therapeutics, Inc.",
    licensor_kr: "헬릭슨테라퓨틱스",
    licensee: "Jeonju Biologics Co., Ltd.",
    licensee_kr: "전주바이오로직스",
    compound: "HLX-229",
    field: "Oncology · Solid Tumor",
    territory: "APAC ex-Japan",
    signed: "2025-08-14",
    effective: "2025-10-01",
    term_years: 10,
    upfront_usd_m: 45,
    milestones_usd_m: 310,
    royalty_low: 0.07,
    royalty_high: 0.12,
    royalty_tiered: true,
    exclusive: true,
    sec: {
      accession: "0001193125-25-248019",
      form: "10-K",
      filer_cik: "0001483934",
      filing_date: "2026-02-14",
      exhibit: "10.17",
    },
    dart: {
      rcept_no: "20250815000421",
      report: "주요사항보고서",
      filer: "전주바이오로직스",
      filing_date: "2025-08-15",
    },
    unified_match: 0.97,
    judge_verdict: "real",
    notable_clause: "Licensee shall pay to Licensor a royalty of <mark>seven percent (7%) up to USD 500M annual net sales, stepping to twelve percent (12%)</mark> above that threshold, for a term of ten (10) years from First Commercial Sale in each Major Market.",
  },
  {
    id: "AGR-04801",
    licensor: "Meridian Biotech AG",
    licensor_kr: "메리디안바이오텍",
    licensee: "Seoul Nano Pharma",
    licensee_kr: "서울나노파마",
    compound: "MRB-017",
    field: "Autoimmune",
    territory: "Worldwide ex-US",
    signed: "2025-06-02",
    effective: "2025-06-02",
    term_years: 12,
    upfront_usd_m: 28,
    milestones_usd_m: 185,
    royalty_low: 0.05,
    royalty_high: 0.09,
    royalty_tiered: true,
    exclusive: true,
    sec: {
      accession: "0000950170-25-071229",
      form: "10-K",
      filer_cik: "0001846018",
      filing_date: "2026-03-03",
      exhibit: "10.22",
    },
    dart: {
      rcept_no: "20250603000188",
      report: "라이센스계약체결",
      filer: "서울나노파마",
      filing_date: "2025-06-03",
    },
    unified_match: 0.94,
    judge_verdict: "real",
    notable_clause: "An upfront cash payment of <mark>twenty-eight million United States Dollars (USD 28,000,000)</mark> shall be due within five (5) business days following the Effective Date.",
  },
  {
    id: "AGR-04790",
    licensor: "Nordgate Chemicals",
    licensor_kr: "노드게이트화학",
    licensee: "한울바이오사이언스",
    licensee_kr: "한울바이오사이언스",
    compound: "NG-CMC-44",
    field: "CMC Platform",
    territory: "Korea",
    signed: "2025-04-22",
    effective: "2025-05-01",
    term_years: 7,
    upfront_usd_m: 8,
    milestones_usd_m: 42,
    royalty_low: 0.04,
    royalty_high: 0.04,
    royalty_tiered: false,
    exclusive: false,
    sec: null,
    dart: {
      rcept_no: "20250425000612",
      report: "기술도입계약",
      filer: "한울바이오사이언스",
      filing_date: "2025-04-25",
    },
    unified_match: null,
    judge_verdict: "real",
    notable_clause: null,
  },
  {
    id: "AGR-04776",
    licensor: "Axil Diagnostics",
    licensor_kr: "액실진단",
    licensee: "Helixon Therapeutics, Inc.",
    licensee_kr: "헬릭슨테라퓨틱스",
    compound: "ADX-PROBE",
    field: "Companion Diagnostic",
    territory: "Worldwide",
    signed: "2025-02-18",
    effective: "2025-03-15",
    term_years: 8,
    upfront_usd_m: 15,
    milestones_usd_m: 95,
    royalty_low: 0.03,
    royalty_high: 0.06,
    royalty_tiered: true,
    exclusive: false,
    sec: {
      accession: "0001564590-25-009871",
      form: "10-K",
      filer_cik: "0001512228",
      filing_date: "2026-02-28",
      exhibit: "10.9",
    },
    dart: null,
    unified_match: null,
    judge_verdict: "real",
    notable_clause: null,
  },
  {
    id: "AGR-04751",
    licensor: "Quant Photonics",
    licensor_kr: "퀀트포토닉스",
    licensee: "Daeryuk Semicon",
    licensee_kr: "대륙반도체",
    compound: "QP-LITHO-12",
    field: "Semiconductor · Lithography IP",
    territory: "Korea, Taiwan",
    signed: "2024-11-30",
    effective: "2025-01-01",
    term_years: 15,
    upfront_usd_m: 120,
    milestones_usd_m: 0,
    royalty_low: 0.025,
    royalty_high: 0.025,
    royalty_tiered: false,
    exclusive: true,
    sec: {
      accession: "0001193125-24-289114",
      form: "10-K",
      filer_cik: "0001000180",
      filing_date: "2025-02-14",
      exhibit: "10.31",
    },
    dart: {
      rcept_no: "20241201000094",
      report: "기술도입계약",
      filer: "대륙반도체",
      filing_date: "2024-12-01",
    },
    unified_match: 0.91,
    judge_verdict: "real",
    notable_clause: "Running royalty equal to <mark>two and one-half percent (2.5%)</mark> of Net Sales of Licensed Products incorporating Licensed IP, payable quarterly.",
  },
  {
    id: "AGR-04729",
    licensor: "Byline Peptides",
    licensor_kr: "바이라인펩타이드",
    licensee: "Meridian Biotech AG",
    licensee_kr: "메리디안바이오텍",
    compound: "BL-PEP-9",
    field: "Metabolic · GLP-1",
    territory: "Worldwide",
    signed: "2024-09-10",
    effective: "2024-11-01",
    term_years: 10,
    upfront_usd_m: 60,
    milestones_usd_m: 420,
    royalty_low: 0.08,
    royalty_high: 0.14,
    royalty_tiered: true,
    exclusive: true,
    sec: {
      accession: "0001628280-24-042277",
      form: "10-K",
      filer_cik: "0001720990",
      filing_date: "2025-02-20",
      exhibit: "10.14",
    },
    dart: null,
    unified_match: null,
    judge_verdict: "real",
    notable_clause: null,
  },
  {
    id: "AGR-04705",
    licensor: "Keppel IP Holdings",
    licensor_kr: "켑펠IP홀딩스",
    licensee: "Jeonju Biologics Co., Ltd.",
    licensee_kr: "전주바이오로직스",
    compound: "KPL-CAR-3",
    field: "CAR-T · Oncology",
    territory: "APAC",
    signed: "2024-07-22",
    effective: "2024-09-01",
    term_years: 12,
    upfront_usd_m: 22,
    milestones_usd_m: 180,
    royalty_low: 0.06,
    royalty_high: 0.10,
    royalty_tiered: true,
    exclusive: true,
    sec: {
      accession: "0001193125-24-189002",
      form: "10-K",
      filer_cik: "0001483934",
      filing_date: "2025-02-14",
      exhibit: "10.28",
    },
    dart: {
      rcept_no: "20240724000517",
      report: "기술도입계약",
      filer: "전주바이오로직스",
      filing_date: "2024-07-24",
    },
    unified_match: 0.88,
    judge_verdict: "ambiguous",
    notable_clause: null,
  },
  {
    id: "AGR-04691",
    licensor: "Orbita Labs",
    licensor_kr: "오르비타랩스",
    licensee: "Seoul Nano Pharma",
    licensee_kr: "서울나노파마",
    compound: "OL-mRNA-7",
    field: "mRNA Platform",
    territory: "Asia",
    signed: "2024-05-14",
    effective: "2024-06-01",
    term_years: 10,
    upfront_usd_m: 18,
    milestones_usd_m: 110,
    royalty_low: 0.05,
    royalty_high: 0.08,
    royalty_tiered: true,
    exclusive: false,
    sec: null,
    dart: {
      rcept_no: "20240516000303",
      report: "기술도입계약",
      filer: "서울나노파마",
      filing_date: "2024-05-16",
    },
    unified_match: null,
    judge_verdict: "real",
    notable_clause: null,
  },
  {
    id: "AGR-04673",
    licensor: "Vantage Imaging",
    licensor_kr: "밴티지이미징",
    licensee: "Helixon Therapeutics, Inc.",
    licensee_kr: "헬릭슨테라퓨틱스",
    compound: "VI-PET-2",
    field: "Imaging · PET Tracer",
    territory: "Worldwide",
    signed: "2024-02-11",
    effective: "2024-04-01",
    term_years: 8,
    upfront_usd_m: 10,
    milestones_usd_m: 70,
    royalty_low: 0.04,
    royalty_high: 0.07,
    royalty_tiered: true,
    exclusive: false,
    sec: {
      accession: "0001564590-24-004412",
      form: "10-K",
      filer_cik: "0001512228",
      filing_date: "2024-02-28",
      exhibit: "10.11",
    },
    dart: null,
    unified_match: null,
    judge_verdict: "real",
    notable_clause: null,
  },
  {
    id: "AGR-04650",
    licensor: "Pallas Therapeutics",
    licensor_kr: "팔라스테라퓨틱스",
    licensee: "한울바이오사이언스",
    licensee_kr: "한울바이오사이언스",
    compound: "PAL-KNK-5",
    field: "Rare Disease",
    territory: "Korea, Japan",
    signed: "2023-12-01",
    effective: "2024-01-15",
    term_years: 10,
    upfront_usd_m: 12,
    milestones_usd_m: 85,
    royalty_low: 0.06,
    royalty_high: 0.09,
    royalty_tiered: true,
    exclusive: true,
    sec: {
      accession: "0001193125-23-301447",
      form: "10-K",
      filer_cik: "0001612008",
      filing_date: "2024-02-14",
      exhibit: "10.21",
    },
    dart: {
      rcept_no: "20231204000877",
      report: "기술도입계약",
      filer: "한울바이오사이언스",
      filing_date: "2023-12-04",
    },
    unified_match: 0.93,
    judge_verdict: "real",
    notable_clause: null,
  },
];

// Royalty distribution (histogram)
const ROYALTY_DIST = [
  { bucket: "0-2%",  count: 112 },
  { bucket: "2-4%",  count: 188 },
  { bucket: "4-6%",  count: 342 },
  { bucket: "6-8%",  count: 411 },
  { bucket: "8-10%", count: 248 },
  { bucket: "10-12%",count: 145 },
  { bucket: "12-15%",count: 68 },
  { bucket: "15%+",  count: 32 },
];

// Field-of-use breakdown
const FIELDS = [
  { field: "Oncology",            agreements: 3814, median_royalty: 0.085, median_upfront_m: 32 },
  { field: "Autoimmune",          agreements: 1207, median_royalty: 0.070, median_upfront_m: 22 },
  { field: "Metabolic",           agreements: 842,  median_royalty: 0.090, median_upfront_m: 40 },
  { field: "Rare Disease",        agreements: 612,  median_royalty: 0.075, median_upfront_m: 15 },
  { field: "CNS",                 agreements: 528,  median_royalty: 0.065, median_upfront_m: 18 },
  { field: "Infectious",          agreements: 394,  median_royalty: 0.055, median_upfront_m: 10 },
  { field: "Diagnostics",         agreements: 287,  median_royalty: 0.040, median_upfront_m: 8 },
  { field: "Semiconductor IP",    agreements: 201,  median_royalty: 0.025, median_upfront_m: 75 },
];

// Recent pipeline events (feed)
const RECENT = [
  { t: "2m",  src: "dart", kind: "ingest",  msg: "rcept_no 20260420000118 · 주요사항보고서 (삼우바이오)" },
  { t: "6m",  src: "sec",  kind: "ingest",  msg: "10-K · Pallas Therapeutics · exhibit 10.21" },
  { t: "14m", src: "uni",  kind: "map",     msg: "unified match 0.94 → AGR-04812 cross-linked" },
  { t: "22m", src: "sec",  kind: "judge",   msg: "LLM verdict: 12 agreements classified · 10 real, 2 ambiguous" },
  { t: "41m", src: "dart", kind: "parse",   msg: "parsed 27 footnotes, 19 clean agreements" },
  { t: "1h",  src: "uni",  kind: "export",  msg: "royalty_observations.csv · 1,546 rows" },
  { t: "2h",  src: "lit",  kind: "ingest",  msg: "CourtListener · In re Helixon v. Pallas (royalty dispute)" },
  { t: "3h",  src: "val",  kind: "compute", msg: "DCF · MRB-017 · median comparable royalty 7.5%" },
];

// Saved queries / user workspaces
const SAVED_QUERIES = [
  { id: "q1", name: "Oncology · APAC · ≥5% royalty",           kr: "항암 · 아시아태평양 · 로열티 5% 이상", n: 214 },
  { id: "q2", name: "Tiered royalty with milestone >USD 200M",  kr: "티어드 로열티 + 마일스톤 2억 USD+",  n: 88 },
  { id: "q3", name: "DART-only (no SEC counterpart)",           kr: "DART 단독 (SEC 대응 없음)",          n: 1207 },
  { id: "q4", name: "GLP-1 / Metabolic",                         kr: "GLP-1 · 대사성",                     n: 141 },
  { id: "q5", name: "Semiconductor IP (non-pharma control)",     kr: "반도체 IP (비제약 대조군)",          n: 201 },
];

// Health strip metrics
const HEALTH = [
  { label: "Pipeline", label_kr: "파이프라인", value: "Running", detail: "last run 00:14 ago · 0 errors", state: "ok" },
  { label: "SEC Ingest", label_kr: "SEC 수집", value: "142,318", detail: "+342 today", state: "ok" },
  { label: "DART Ingest", label_kr: "DART 수집", value: "28,976", detail: "+87 today", state: "ok" },
  { label: "Unified Map", label_kr: "통합 매핑", value: "97.1%", detail: "18,490 / 19,054", state: "ok" },
  { label: "Judge Precision", label_kr: "판정 정밀도", value: "0.81", detail: "n=412 holdout · κ=0.76", state: "warn" },
];

window.LICENSE_DATA = { SNAPSHOT, AGREEMENTS, ROYALTY_DIST, FIELDS, RECENT, SAVED_QUERIES, HEALTH };
